### ISSUE TITLE
Group explorer: groups near you widget

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1006]
"(Groups) near you" widget for showing nearby groups, impacted by the group-type filter for the overall view

- [ ] A 'map sub-view', or link to the map filtered for this

**Comment by thomasgwatson** [comment]
I think the discussion required here is confirming whether we want to have this in the group explorer.

The `GroupSearch` component has the functionality for users to discover this. However, that does require them to interact with it; it might not initially be obvious to users that they can find groups near them with the `GroupSearch`. The benefit of keeping a specific `groups near you` widget is that we would nudge users towards considering these groups, a segment of relevant groups that they might otherwise miss. The addition of a map-view for this widget could also provide another avenue of spatial discovery for users, although we would need to figure out how pagination would work here

**Comment by tibetsprague** [comment]
after discussing this is still something we want
