### ISSUE TITLE
Attaching URL links on posts using attach feature

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1034]
Clicked on attach w/in the post and uploaded a URL. 

It uploads and saves as "convert" on the post. Rather than taking one to the link when clicked, it downloads the link. 

Links work fine when included in the body of the post. 
<img width="890" alt="Uploading a link to a post" src="https://user-images.githubusercontent.com/92816219/149041763-be6f5420-89d9-4144-9094-6eb5d454be2b.png">

**Comment by lorenjohnson** [comment]
I agree this is not ideal, nor what would be expected. This is how it’s implemented at this time. “Attaching” a Google Doc converts it to Open Office Document and attaches that to the Post. There is some logic to that, but it could use a disclaimer perhaps or otherwise be disabled as a valid option in our file upload dialog. 

To get to the more expected flow a user can share a Google Doc link vs upload. * It would of course be helpful if the Post link previews did nice things with a Google Doc/Sheet, but I think right now the preview is pretty basic.
