### ISSUE TITLE
@mentions of current user appear in different color

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1308]
specifically #FDB549

**Comment by lorenjohnson** [comment]
I think this will be a simple addition to `ClickCatcher` (probably should be renamed `HyloHTMLHandler`) which adds an element data attribute or CSS class to `span.mention` when the `data-id` of any of those elements matches `currentUser.id`.  Then add a global typography stylesheet, and that should be it. I will need to make the symmetrical change in the similar spot in HyloApp.

**Comment by tibetsprague** [comment]
https://www.figma.com/file/ScahK1CtEDyNbJ5jMM1eg3/Topic-Based-Chat?node-id=2%3A1336&t=dTMixvstpqOncDHb-0

**Comment by thomasgwatson** [comment]
@lorenjohnson ClickCatcher just wraps other content (like HyloEditor), and doesn't parse it, as far as I understand. Is that really where this change is easiest?

I would have through HyloEditor was going through and doing the current styling highlight for mentions but I don't know how tiptap works and how it integrates into our setup. Looking at tiptap now.

**Comment by lorenjohnson** [comment]
@thomasgwatson totally fair on ClickCatcher :) -- it will only know it's a mention once a click has happened. It also can't be done in the editor though as the Current User will only be current while creating the content. This should go here though:

https://github.com/Hylozoic/hylo-node/blob/c3012043542786e493380a3c66cc03a91104cff8/api/services/RichText.js#L56

Adding the CSS class to the element as I was recommending above to mentions that are for the currently authorized user. 

* We will need to send the `currentUserId` to this this function from the few places this is called, or otherwise get it from state in this function.

**Comment by thomasgwatson** [comment]
oooo, yes, checking out RichText now
