### ISSUE TITLE
When switching communities stay on current view

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#511]
For example if you are currently looking at the map then when using the navigation drawer to switch communities, open up the new community on the map view. This should work the same for al the views (projects, events, directory...). 

This should be doable just using the Redux state, we may want a new reducer for it? UI or something? Or maybe this goes in the PrimaryLayout reducer?

**Comment by pospi** [comment]
Alternative implementation: figure out current view from route, update route directly on change without any other state being kept in Redux.

**Comment by lorenjohnson** [comment]
> Alternative implementation: figure out current view from route, update route directly on change without any other state being kept in Redux.

Generally, yes. The route matching keys should be fairly reliable at this point and built to make this possible or easy. The navigation URL helpers and where they're used is a good place to put some focus. It's a bit of a bad smell to me to create another state layer for this. 

Hi @pospi !

**Comment by pospi** [comment]
First pass at this seems to be working pretty well, though I ran into some complexity with the "All Topics" modal. Its logic has been changed to return to the root of your current community context upon closing the popup- this allows community switching with the topics page to work (otherwise it would return you to the previously viewed community); but does mean that closing "All Topics" always takes you back to the root of the community, rather than the last section you were viewing.

If this is sub-optimal, the alternative straightforward solution would be to exclude the "topics" section from `getViewContextForCurrentRoute` so that switching communities with "topics" open takes you to the main community page of your destination, rather than into "topics". **Currently any sub-path gets retained in the redirect**, and I might not be aware of some other weird ones, so if this should be whitelisted let me know.

Failing that, the only solution would be to trigger a new redux action which injects an extra step into the navigation so that closing such modals (which look for the previous route) works as expected. That is likely quite brittle and complex, but I could be wrong.

No tests yet, let me know if I've missed any necessary due diligence.

**Comment by pospi** [comment]
Further recommendation: I can see the navigation code has gotten a bit out of hand, and based on my own past experience I blame `connected-react-router` for introducing ambiguity as to where the source of truth for navigation state lies.

Ideally we should remove that module entirely and consider the router as the only source of truth for interpreting navigation state. That would remove a lot of ambiguity and complexity in all this routing logic.

**Comment by pospi** [comment]
Decision from @tibetsprague - if switching contexts with "topics" open, route switches to the root of the new community rather than the topics page. This way it won't interfere with navigation when switching to topics on the map.
