### ISSUE TITLE
New profile layout

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#621]
Move name, location, tagline, about me, social links all together in one place, and make social links more obvious

https://www.figma.com/file/XxEThPA1vhqgs26d4uWhvy/Profiles?node-id=0%3A1

**Comment by tibetsprague** [comment]
![image](https://user-images.githubusercontent.com/3741/94482434-21dc4680-018e-11eb-924e-2f04051d7487.png)

**Comment by lorenjohnson** [comment]
* User "bio" / description not shown here but will incorporate in some way below the "short bio"
* TBD on how phone number or email address display after clicking the round icon
* Custom fields will be anticipated in the design / stylesheet, but not yet implemented

**Comment by tibetsprague** [comment]
@brodeur we will want a link to Message this person on Hylo. maybe to the left of the email button?

**Comment by lorenjohnson** [comment]
A few delivery notes and lingering design questions/issues:

* What should the email and phone buttons do?  Currently set to do `mailto:` and `tel:`, respectively.
* Would like to link the Member location to a map search but don't see how to do that?
* Currently no place for "* Community manager" role label in this design, should we still be showing this? If so, where?
* This update eliminates the sidebar on the Member Profile where Skills and the Message button used to be...

@brodeur @tibetsprague

**Comment by tibetsprague** [comment]
thats true, there is not yet a way to link to a location on the map, we still need to have full URL control over the map https://github.com/Hylozoic/hylo-evo/issues/606

**Comment by tibetsprague** [comment]
The ellipsis menu should always go to the far right ![image](https://user-images.githubusercontent.com/3741/96029005-e177fc00-0e0e-11eb-8aee-d111856283b9.png)

**Comment by tibetsprague** [comment]
when editing skills it would be nice to see the current ones: 
![image](https://user-images.githubusercontent.com/3741/96029777-f86b1e00-0e0f-11eb-8224-b084bd39ffcf.png)

**Comment by lorenjohnson** [comment]
> when editing skills it would be nice to see the current ones:
> ![image](https://user-images.githubusercontent.com/3741/96029777-f86b1e00-0e0f-11eb-8224-b084bd39ffcf.png)

For sure that is a bug, wasn't aware it wasn't. Will fix.

**Comment by lorenjohnson** [comment]
> The ellipsis menu should always go to the far right ![image](https://user-images.githubusercontent.com/3741/96029005-e177fc00-0e0e-11eb-8aee-d111856283b9.png)

Ok. This of course wasn't anywhere in the design and I put it where I thought it made the most sense. I can put it to the right if that's the final decision :)

**Comment by tibetsprague** [comment]
@brodeur updated the designs to answer some of these questions too

**Comment by tibetsprague** [comment]
you can see the new edit profile button, the place for the tag line above the about me, and the hover for the email. we decided that all the links (and contact email and phone) should appear on hover, with a copy button. clicking on the email or phone in the hover box will do the mailto: or tel: or go to the link

**Comment by lorenjohnson** [comment]
> you can see the new edit profile button, the place for the tag line above the about me, and the hover for the email. we decided that all the links (and contact email and phone) should appear on hover, with a copy button. clicking on the email or phone in the hover box will do the mailto: or tel: or go to the link

* I moved the action menu to the right, changed the Pillbox / Skills & Interests editor and search to be at the bottom instead of the top and no longer overlap the existing tags. That is in the PR and ready to go.

* So you want an onhover showing the value plus a "Copy" button for phone, email, and all social links? Can I get a basic design mock of this? Even a rough sketch or a link to another produce that has a similar design pattern is fine, but seeing this visually would be helpful.

* You are saying you want an additional "Edit Profile" icon? Can you point me to which icon and where you want this on the bar. Also, do we keep the "..." menu with the single "Block User" item?

**Comment by lorenjohnson** [comment]
Oh I see now the earlier note and the additions in Figma.

**Comment by lorenjohnson** [comment]
* Tagline / Bio: Currently if there is both a tagline and a bio it shows the bio only. If there is only one, it only shows the one. In this updated design is the formatting for the tagline always the title font and bio body phone regardless of if they both exist? I am assume yes, that would make sense to me, though a title font tagline might look funny without a bio? Just want to confirm this stuff to avoid any unnecessary cycles.

* Do we want "Edit Profile" in the "..." menu as well as the Banner onHover button? 

* Have you guys reviewed what happens when there is no Banner image? I currently have a gradient in there, let me know if something else was supposed to happen. 

** FYI / Thought --  The hover / copy button for the links will push things into next week on this feature as I'm going to be unplugging after addressing some open loops today. If we want to push this current iteration this week, leaving the remaining refinements for next week, I think it's at a workable place for release now.

**Comment by lorenjohnson** [comment]
Also, is the intention of the "Edit Profile" button on the banner that it's shown all the time on the Current User's profile vs on hover? Realized that makes more sense and is perhaps what was intended in the mock-up.
