### ISSUE TITLE
Fix access to Facebook avatar images

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#667]
https://developers.facebook.com/blog/post/2020/10/14/required-migration-token-based-access-user-picture-oEmbed-endpoints/

**Comment by lorenjohnson** [comment]
Fixed by directly updating data in posts.avatar_url where the user avatar was linking to Facebook, and by updating `hylo-node` with correct link template for future Facebook sign-ups. 

The PR:

https://github.com/Hylozoic/hylo-node/pull/554

The query used to directly updated the database was the following (where `app-id` and `client-token` are actual values) -- this has already been ran:

```
UPDATE users
SET avatar_url = CONCAT (avatar_url, '&access_token={app-id}|{client-token}')
WHERE avatar_url LIKE 'https://graph.facebook.com/%'
```
