### ISSUE TITLE
Data export of member directory

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#796]
https://www.figma.com/file/bQVvU24wfa8H0WLAnAl1ym/Export-Data?node-id=0%3A1&viewport=160%2C-496%2C0.38377535343170166

Settings page for export

**Comment by pospi** [comment]
Just confirming differences between this design & what we're targeting for MVP.

- Should we omit the "Data Set" block for now, since MVP is for per-group export and all-groups export may be quite large datasets?
- What options should the "Data Type" block make available? Or does it just do "export members" for now, in which case no options and just a button?

**Comment by pospi** [comment]
@tibetsprague just confirming differences between this design & what we're targeting for MVP.

- Should we omit the "Data Set" block for now, since MVP is for per-group export and all-groups export may be quite large datasets?
- What options should the "Data Type" block make available? Or does it just do "export members" for now, in which case no options and just a button?

**Comment by tibetsprague** [comment]
Yeah @pospi for now we can literally just have an export button that says export member information

**Comment by tibetsprague** [comment]
Hmm after further discussion we may want the all groups export too... definitely start with 1 group though. Seems like all groups might need to run in a background job and be polled
