### ISSUE TITLE
Event suggested invites list not showing all members, only first few, search broken too

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#935]
The suggested people to invite only shows a short list, you should be able to scroll it to load more people

**Comment by thomasgwatson** [comment]
Looking at this again.

As far as I can tell I can:
- type some input and get a range of folks I can invite
- scroll down that list of people

![image](https://user-images.githubusercontent.com/5193218/140567597-fb943ace-e370-40be-bb26-fa6ef908a9ae.png)

So it *seems* like it works.

However, I notice that in the same context, that the same input can yield different results

When I first type in `a`, I get six results

![image](https://user-images.githubusercontent.com/5193218/140568413-dbff49cf-2489-4735-ab64-97e092e242e9.png)

I type in a range of different single letters, `b`, `c`, `d` and then go back to `a`. Most time when I go back to `a`, there are more results, more members to choose from. I got up to like 35 results.

![image](https://user-images.githubusercontent.com/5193218/140568365-7b3d187f-765d-4ecf-ac56-41c5c9af1991.png)

Sounds like the fetch and the select are out of sync: the fetch doesn't return the full list. Will check into the the logic on the backend. Also, the `PeopleQuery` doesn't have the `hasMore` property, which I believe is the convention for paging in our graphQL queries

**Comment by thomasgwatson** [comment]
Okay...

So, we *might* not be using the right approach for text search for users. 

This article explains some of the surrounding details: https://about.gitlab.com/blog/2016/03/18/fast-search-using-postgresql-trigram-indexes/

Basically the regular postgres full text search is best for natural language (since part of its optimization is to recognize grammatical patterns in text based on the declared language and normalize the text to aid searching). But this doesn't make sense in the context of names, and so searching for all the names with an `a` in them yields unsatisfying results.

The article describes a trigram technique available as a special index for Postgres (yay postgres, its so cool), which uses a different query pattern but is actually more straight forward that the full text search. I suspect that will improve the quality of our member lookup.

Also important to note about internationalization here: the full text search is dependent on us specifying a specific language and it won't work cleanly if we have different languages in the same search. Something to think about for the future

**Comment by tibetsprague** [comment]
@thomasgwatson this is still not what I mean :) What I mean is when you click on Invite for an event you see this list of suggested people to invite. But it only shows a few people. Scrolling the list should load more people, but it doesnt. However, I thought this was a bug but looking at the code it was just never implemented! But it also looks like you found another issue :) So it sounds like we need two tickets, one for that you found, and one for this feature that I want to add of being able to scroll and load more people to invite without having to remember their name and search for them in the Invite dialog  
![image](https://user-images.githubusercontent.com/3741/141173259-d4c389f3-b30a-4a1c-b50f-0fd49856a2e6.png)

**Comment by thomasgwatson** [comment]
ahhh ok, good to know
