### ISSUE TITLE
Make initial app load faster

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#952]
Right now it can take a long time before the app appears (9 seconds on web, 17 seconds in app for Tibet, probably because he's in 70 groups), 

One idea: we should not wait to load all the data before showing the basics. Start by loading the basic info for the current group, then load everything else in separate queries: posts, notifications, messages, other groups for the nav bar...

Other things to look into: Redux ORM being slow, missing Postgres indexes, better postgresql queries, benchmark GraphQL queries...

**Comment by lorenjohnson** [comment]
First step in how I'm approaching this will be to gather some concrete data to ground the effort:

- [] Exploration of Networks tab in the timings tab in Web Console looking for the biggest time sucks. We can see individual API calls (graphql), render, and waiting times pretty quickly here. 
- [] If from that exploration it deems it useful I'll also setup some independent graqphql benchmarking on key queries (e.g. currentUser / `me`) removing the front-end from the equation. This should also give us a relatively simple way to benchmark the potential gains on the API side of doing incremental queries vs more comprehensive (i.e. splitting-up the `me` query).
- [] A cursory look at backend query composure initiated by key graphql resolvers to see if there is any de-duping or otherwise optimization of queries within any particular critical resolver path (e.g. again, the `Me` resolver as called by `currentUser` fetch)
- [] Course is still to be set from here, but I imagine from these first 2 steps we'll have enough information to benefit from some front-end modifications to try-out potential benefits of splitting the bigger queries up more, etc.

\* I will be updating this comment for a bit with amendments to this plan as I get into the work and the course gets more clear.

**Comment by lorenjohnson** [comment]
A bit more follow-up on this. I went one step further in to look at our WebPack stats and a couple of things jumped-out a bit:

1) `faker.js` used for our `samplePost` is taking up a little more than 10% of our total bundle size at around 1.2M raw and a similar proportion in the zipped down size. It might be worthwhile generating static fake data for `samplePost`. We can use faker still to generate static stuff for the samplePost and as long as it's not ever running after the actual build it will be shaken out. 
2) Not too surprisingly the map related libraries are in aggregate taking a little over 3M raw, not sure how much once compressed. It would likely make sense to selectively load these triggered by the route (there is a somewhat standard way do this it seems with `react-router` or at least configure WebPack to bundle them separately.

There are other much smaller things we could do that are probably not worth a lot. Doing something about the above 2 though would make a notable impact on the initial load time entering anywhere on the site, except the map (though we'd have some improvement there as well in removing faker), this of course would be even more true in slow Internet connection scenarios.
