### ISSUE TITLE
Invite join questions not working?

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#992]
Anita Halcyon of HACC and Krisha were testing the invite/join questions for private groups; the HACC group is private and requires join questions. When Krisha requested to join, no questions popped and there was no option to respond.

**Comment by tibetsprague** [comment]
@KrishaTerranIO can you ask Anita for an example post with a location that is not appearing on the map? Looking at the posts in the group i dont see any with locations.

**Comment by tibetsprague** [comment]
so, the one main issue with join questions right now is they dont appear if you are invited to join, only if you request to join from the map or group landing page. So they need to send people to https://www.hylo.com/groups/holochain-advocates to join instead of giving them an invite link. Make sense? @KrishaTerranIO i can show you
